agency/urls.py
from django.urls import include, path, re_path

from . import views

urlpatterns = [

	path('request_pick_up/', views.request_pick_up, name='request_pick_up'),
	path('<id>/eWaste_details/', views.eWaste_details, name='eWaste_details'),
	path('<id>/eWaste_Image/', views.eWaste_image, name='eWaste_image'),
	path('<id>/submit_comment/', views.comment, name='comment'),
	path('int<id>/create_agency_profile/', views.create_agency_profile, name='create_agency_profile'),
	path('agencies/', views.agency_list, name='agencies'),
	path('<id>/agency/', views.agency_details, name='agency_details'),
	path('ewaste_status_update/', views.update_waste_status, name='update_waste_status'),
]

eWasteManager/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from accounts.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('offline/', homepage, name='offline'),
    path('accounts/', include('accounts.urls')),
    path('agents/', include('agency.urls')),
    path('', include('pwa.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.enable_nav_sidebar = False

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser, User
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver

from ckeditor.fields import RichTextField
from phonenumber_field.modelfields import PhoneNumberField

from .managers import CustomUserManager


class User(AbstractUser):
	username = None
	email = models.EmailField(_('email address'), unique=True)
	is_customer = models.BooleanField(default=False, help_text='Designate the user as a customer')
	is_collection_agent = models.BooleanField(default=False, help_text='Designate the user as a collection agent')

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = CustomUserManager()

	def __str__(self):
		return self.email


class CustomerProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, unique=True, related_name='customerprofile')
	username = models.CharField(max_length=75, blank=True)
	first_name = models.CharField(max_length=75)
	last_name = models.CharField(max_length=75)
	other_name = models.CharField(max_length=75, blank=True)
	photo = models.ImageField(blank=True, upload_to='users/customers/%Y/%m/%d' )
	email = models.EmailField()
	email_confirmed = models.BooleanField(default=False)
	phone = PhoneNumberField()
	address = models.CharField(max_length=255)
	city = models.CharField(max_length=75)
	location = models.CharField(max_length=75, blank=True)
	is_verified = models.BooleanField(default=False)
	updated_on = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return unicode(self.username)

	def __str__(self):
		return self.username
		
	# def get_absolute_url(self):
	# 	return reverse('accounts:shopper_profile', args=[str(self.id)])


class CollectionAgentProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='agentprofile')
	# agent_id = models.CharField(help_text='Unique ID for a merchant', max_length=25)
	first_name = models.CharField(max_length=75)
	last_name = models.CharField(max_length=75)
	other_name = models.CharField(max_length=75, blank=True)
	photo = models.ImageField(blank=True, upload_to='users/agents/%Y/%m/%d' )
	email = models.EmailField()
	email_confirmed = models.BooleanField(default=False)
	phone = PhoneNumberField()
	permanent_address = models.CharField(max_length=255)
	city = models.CharField(max_length=75)
	location = models.CharField(max_length=75, blank=True)
	about = models.TextField()
	date_of_birth = models.DateField(auto_now_add=True)
	is_verified = models.BooleanField(default=False)
	updated_on = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return unicode(self.username)

	def __str__(self):
		return self.email

	# def get_absolute_url(self):
	# 	return reverse('accounts:shopper_profile', args=[str(self.id)])

templates/accounts/agents/admin/create_agency_profile.html
{% extends 'base_edit_form.html' %}

{% block title %}Agency Profile {% endblock %}
{% block header %}Agency Profile {% endblock %}
{% block form%} 
	{% csrf_token %}
	{{form.as_p}}
	{{form.media}}
{% endblock %}

templates/accounts/agents/admin/index.html
{% extends 'base.html' %}
{% block styles %}
	<style type="text/css">
		.card{
			border-style: solid;
			border-radius: 1em;
			padding: 1em;
			margin: 1em;
		}
		#shipping {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        #shipping td, #shipping th {
          border: 1px solid #ddd;
          padding: 8px;
        }

        #shipping tr:nth-child(even){background-color: #f2f2f2;}

        #shipping tr:hover {background-color: #ddd;}

        #shipping th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #04AA6D;
          color: white;
        }
        .countryselectwidget{
        	width: 50%;
        }
        form input{
            padding: 11px 20px;
            margin: 8px 0;
            width: 100%;
            box-sizing: border-box;
        }
	</style>
	<script type="text/javascript">
	    var user = '{{request.user}}'
	    function getToken(name) {
	        var cookieValue = null;
	        if (document.cookie && document.cookie != '') {
	            var cookies = document.cookie.split(';');
	            for (var i = 0; i < cookies.length; i++) {
	                var cookie = cookies[i].trim();
	                // Does this cookie string begin with the name we wanr?
	                if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                    break;
	                }
	            }
	        }
	        return cookieValue;
	    }
	    var csrftoken = getToken('csrftoken');
	</script>
{% endblock %}
{% block content %}
<div>
	<h1>Agency Dashboard</h1>
	<h2>Agency: {{agency}}</h2>
	<h3>Agent: {{agent_profile}}</h3>
	<div class="card">
		<h4>Pick Up Requests</h4>
		<div>
			{% if pick_up_requests%}
			<table id="shipping">
				<tr>
					<th>Item</th>
					<th>Client</th>
					<th>Contact Email</th>
					<th>Phone Contact</th>
					<th>Status<small> Click to update
					</small></th>
					<th>Address</th>
					<!-- <th>GPS</th> -->
					<th>Date</th>
				</tr>
				<div class="alert{{item.id}} alert-success" style="text-align: center; display: none;"></div>
				{% for request in pick_up_requests %}
				<tr>
					<td><a href="{% url 'eWaste_details' request.id %}">{{request.ewaste}}</a></td>
					<td>{{request.client}}</td>
					<td><a href="mailto:{{request.email}}">{{request.email}}</a></td>
					<td><a href="tel: {{request.phone_contact}}">{{request.phone_contact}}</a></td>
					<td>
						<a href="#">{{request.status}}</a>
						{% if request.status == 'Pending' %}
							<div class="action{{request.id}}">
								<button type="button" class="btn btn-primary confirmBtn" confrimBtn data-request= "{{request.id}}" data-action="confirm">
							  	Update to Picked
								</button>
							</div>
						{% endif %}
					</td>
					<td>{{request.address}}</td>
					<!-- <td>{{request.location}}</td> -->
					<td>{{request.uploaded}}</td>
				</tr>
				{% endfor %}
			</table>
			{% else %}
			<h3>No Request made to the Agency Yet</h3>
			{% endif %}
		</div>	
	</div>
</div> 	
{% endblock %}
{% block scripts %}
	<script type="text/javascript">
		var btn = document.getElementsByClassName('confirmBtn')
		for (var i = 0; i < btn.length; i++) {
		    btn[i].addEventListener('click', function(e) {
		        e.preventDefault();
		        var ewasteId = this.dataset.request
		        var action = this.dataset.action
		        console.log('ewasteId:', ewasteId, 'action:', action)
		        updateEWasteStatus(ewasteId, action)

		    })
		};
		function updateEWasteStatus(ewasteId, action, order) {
		    console.log('Attempting to Send Data');

		    if (action == 'confirm') {
		        var url = '/agents/ewaste_status_update/'
		    }
		    console.log("Sending...");
		    $.ajax({
		        headers: { 'X-CSRFToken': csrftoken },
		        type: 'POST',
		        url: url,
		        data: { 'ewasteId': ewasteId, 'action': action, 'order': order},
		        beforeSend: function() {
		            var action = '.action'
		            action += ewasteId
		            console.log(action);
		            $(action).hide();
		        },
		        success: function update_content(str) {
		            console.log("Status Updated!");
		            var html = ``;
		            var injection = '.alert';
		            injection += ewasteId;
		            console.log(injection);
		            $(injection).show();
		            html += `<p>You have updated an Items Status!</p>`;
		            document.querySelector(injection).innerHTML = html;
		            
		        },
		        error: function() {
		            console.log("Error Updating Item Status!");
		        },
		    });
		};
	</script>
{% endblock %}

templates/accounts/agents/admin/profile.html
{% extends 'base.html' %}

{% block content %}
<div style="margin: 2em; padding: 1em;">
	<h1>Agent Profile</h1>
	<h2>Agency: {{agency}}</h2>
	<h3>Agent email: {{agent_profile}}</h3>
	<a href="{% url 'create_agency_profile' agency.id %}">Complete Agency Profile</a>
</div> 	
{% endblock %}

templates/accounts/agents/admin/profile_edit_form.html
{% extends 'base.html' %}

{% block title %}Create Agency Profile {% endblock %}
    {% block styles %}
        <style type="text/css">
            input, #id_about{
                display: block;
                width: 100%;
                height: calc(1.5em + 0.75rem + 2px);
                padding: 0.375rem 0.75rem;
                font-size: 1rem;
                font-weight: 400;
                line-height: 1.5;
                color: #6e707e;
                background-color: #fff;
                background-clip: padding-box;
                border: 1px solid #d1d3e2;
                border-radius: 0.35rem;
                transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
            }
            @media (prefers-reduced-motion: reduce) {
              input {
                transition: none;
              }
            }

            input::-ms-expand {
              background-color: transparent;
              border: 0;
            }

            input:focus {
              color: #6e707e;
              background-color: #fff;
              border-color: #bac8f3;
              outline: 0;
              box-shadow: 0 0 0 0.2rem rgba(78, 115, 223, 0.25);
            }

            input::-webkit-input-placeholder {
              color: #858796;
              opacity: 1;
            }

            input::-moz-placeholder {
              color: #858796;
              opacity: 1;
            }

            input:-ms-input-placeholder {
              color: #858796;
              opacity: 1;
            }

            input::-ms-input-placeholder {
              color: #858796;
              opacity: 1;
            }

            input::placeholder {
              color: #858796;
              opacity: 1;
            }

            input:disabled, input[readonly] {
              background-color: #eaecf4;
              opacity: 1;
            }

            selectinput:focus::-ms-value {
              color: #6e707e;
              background-color: #fff;
            }
            #id_about{
                height: auto;
            }
            #photo-clear_id{
                width: 20%;
                height: calc(.5em + 0.25rem + 1px);
                padding: 0.375rem 0.75rem;
                font-size: .5rem;
                display: flex;
            }
            #id_photo{
                border: none;
            }
        </style>
    {% endblock %}
{% block content %} 
<div style="margin: 3em;">
	<div style="padding: 2em;">
		<h2>Complete your Profile</h2>	
	</div>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token%}
		{{form.as_p}}
		<input type="submit" name="submit" placeholder="Save"style="background-color: #0a0f3d; color: snow; font-weight: bold;">
	</form>
</div>
{% endblock %}